apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-personalia-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-personalia-api-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-personalia-api/internal/isAlive
    initialDelay: 15
  readiness:
    path: /tms-personalia-api/internal/isReady
    initialDelay: 15
  prometheus:
    enabled: true
    path: /tms-personalia-api/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dittnav-api
        - application: tms-min-side-proxy
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "100m"
      memory: 580Mi
